apiVersion: v1
kind: Secret
metadata:
  name: miro-secrets
  labels: {{- include "miro-workflows.labels" . | nindent 4 }}
type: Opaque
stringData:
  database-url: {{ .Values.database.url | quote }}
  token-signing-secret: {{ .Values.auth.tokenSigningSecret | quote }}
  token-encryption-key: {{ .Values.auth.tokenEncryptionKey | quote }}
  webhook-secret: {{ .Values.webhook.secret | quote }}
  {{- if .Values.auth.miro.clientSecret }}
  miro-oauth-client-secret: {{ .Values.auth.miro.clientSecret | quote }}
  {{- end }}
